// the first object of DummyComments array is the representation of how you should design your comment format in order for the Comments component to work
export const dummyComments = [
  {
    commentId: "12jhg762dsXEdajgDcaf",
    username: "Abdul Haseeb",
    userId: "hasdD76Fnmab7adqpoHW8",
    avatar: "",
    likes: {
      numbers: 5,
      usersLiked: [
        { Ali: "hasdD76Fnmfe7adqpoHW8" },
        { faraz: "hasdD76Fnmfe7adqewyHW8" },
        { ammar: "hasdD76Fnmfe7aUNqwyHW8" },
        { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
        { hassan: "msidD76Fnmfe7aUNqwyHW8" },
      ],
    },
    comment: "hello",
    replies: [
      {
        commentId: "12jhg762qwXEdajgDcaf",
        username: "Ali Mehdi",
        userId: "hasdD76Fnmfe7adqpoHW8",
        avatar: "",
        likes: {
          numbers: 4,
          usersLiked: [
            { faraz: "hasdD76Fnmfe7adqewyHW8" },
            { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
            { hassan: "msidD76Fnmfe7aUNqwyHW8" },
            { "abdul Haseeb": "hasdD76Fnmab7adqpoHW8" },
          ],
        },
        comment: "hi haseeb",
      },
      {
        commentId: "12jhg762dsXEdmkgDcaf",
        username: "Abdul Haseeb",
        userId: "hasdD76Fnmab7adqpoHW8",
        avatar: "",
        likes: {
          numbers: 1,
          usersLiked: [{ Ali: "hasdD76Fnmfe7adqpoHW8" }],
        },
        comment: "i am fine",
      },
    ],
  },
  {
    commentId: "12jhg798dsXEdajgDcaf",
    username: "Abdul Haseeb",
    userId: "hasdD76Fnmab7adqpoHW8",
    avatar: "",
    likes: {
      numbers: 30,
      usersLiked: [
        { Ali: "hasdD76Fnmfe7adqpoHW8" },
        { faraz: "hasdD76Fnmfe7adqewyHW8" },
        { ammar: "hasdD76Fnmfe7aUNqwyHW8" },
        { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
        { hassan: "msidD76Fnmfe7aUNqwyHW8" },
        { Ali: "hasdD76Fnmfe7adqpoHW8" },
        { faraz: "hasdD76Fnmfe7adqewyHW8" },
        { ammar: "hasdD76Fnmfe7aUNqwyHW8" },
        { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
        { hassan: "msidD76Fnmfe7aUNqwyHW8" },
        { Ali: "hasdD76Fnmfe7adqpoHW8" },
        { faraz: "hasdD76Fnmfe7adqewyHW8" },
        { ammar: "hasdD76Fnmfe7aUNqwyHW8" },
        { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
        { hassan: "msidD76Fnmfe7aUNqwyHW8" },
        { Ali: "hasdD76Fnmfe7adqpoHW8" },
        { faraz: "hasdD76Fnmfe7adqewyHW8" },
        { ammar: "hasdD76Fnmfe7aUNqwyHW8" },
        { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
        { hassan: "msidD76Fnmfe7aUNqwyHW8" },
        { Ali: "hasdD76Fnmfe7adqpoHW8" },
        { faraz: "hasdD76Fnmfe7adqewyHW8" },
        { ammar: "hasdD76Fnmfe7aUNqwyHW8" },
        { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
        { hassan: "msidD76Fnmfe7aUNqwyHW8" },
        { Ali: "hasdD76Fnmfe7adqpoHW8" },
        { faraz: "hasdD76Fnmfe7adqewyHW8" },
        { ammar: "hasdD76Fnmfe7aUNqwyHW8" },
        { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
        { hassan: "msidD76Fnmfe7aUNqwyHW8" },
      ],
    },
    comment: "hello",
    replies: [
      {
        commentId: "12jhg762qwXEdajgDcaf",
        username: "Ali Mehdi",
        userId: "hasdD76Fnmfe7adqpoHW8",
        avatar: "",
        likes: {
          numbers: 3,
          usersLiked: [
            { faraz: "hasdD76Fnmfe7adqewyHW8" },
            { "agha sajjad": "hasdD76FOGce7aUNqwyHW8" },
            { hassan: "msidD76Fnmfe7aUNqwyHW8" },
          ],
        },
        comment: "hi haseeb",
      },
      {
        commentId: "12jhg762dsXEdmkgDcaf",
        username: "Abdul Haseeb",
        userId: "hasdD76Fnmab7adqpoHW8",
        avatar: "",
        likes: {
          numbers: 1,
          usersLiked: [{ Ali: "hasdD76Fnmfe7adqpoHW8" }],
        },
        comment: "i am fine",
      },
    ],
  },
  {
    commentId: "12jhg762dsXEdmgyDcaf",
    username: "Abdul Haseeb",
    userId: "hasdD76Fnmab7adqpoHW8",
    avatar: "",
    likes: {
      numbers: 1,
      usersLiked: [{ Ali: "hasdD76Fnmfe7adqpoHW8" }],
    },
    comment: "hello",
    replies: [],
  },
  {
    commentId: "12jhg762dsMQdajgDcaf",
    username: "Abdul Haseeb",
    userId: "hasdD76Fnmab7adqpoHW8",
    avatar: "",
    likes: {
      numbers: 1,
      usersLiked: [{ Ali: "hasdD76Fnmfe7adqpoHW8" }],
    },
    comment: "hello",
    replies: [],
  },
  {
    commentId: "12lkj762dsXEdajgDcaf",
    username: "Abdul Haseeb",
    userId: "hasdD76Fnmab7adqpoHW8",
    avatar: "",
    likes: {
      numbers: 1,
      usersLiked: [{ Ali: "hasdD76Fnmfe7adqpoHW8" }],
    },
    comment: "hello",
    replies: [],
  },
  {
    commentId: "12jhg762dsXEdajgDzxc",
    username: "Abdul Haseeb",
    userId: "hasdD76Fnmab7adqpoHW8",
    avatar: "",
    likes: {
      numbers: 1,
      usersLiked: [{ Ali: "hasdD76Fnmfe7adqpoHW8" }],
    },
    comment: "hello",
    replies: [],
  },
  {
    commentId: "12jhg762dsXEdaftDcaf",
    username: "Abdul Haseeb",
    userId: "hasdD76Fnmab7adqpoHW8",
    avatar: "",
    likes: {
      numbers: 1,
      usersLiked: [{ Ali: "hasdD76Fnmfe7adqpoHW8" }],
    },
    comment: "hello",
    replies: [],
  },
];
